name:                i3ws
version:             0.1.0.0
github:              "myme/i3ws"
license:             BSD3
author:              "Martin Myrseth"
maintainer:          "@myme"
copyright:           "2019 Martin Myrseth"

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/myme/i3ws#readme>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src/
  dependencies:
    - aeson
    - binary
    - bytestring
    - containers
    - fa
    - i3ipc
    - network
    - process
    - text
    - utf8-string

executables:
  i3ws:
    main: Main.hs
    source-dirs: app/
    dependencies:
      - i3ipc
      - i3ws

tests:
  i3ws-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - aeson
      - bytestring
      - i3ipc
      - i3ws
      - hspec
      - QuickCheck
